GRID_SIZE = 5
N_GEMS = 3
MAX_STEPS = GRID_SIZE**2 * 4

REWARD_GOAL = 20
REWARD_STEP = -1
REWARD_GEM = 5
REWARD_INVALID = -1 

START = (0,0)
GOAL = (GRID_SIZE-1, GRID_SIZE-1)
ACTIONS = [(-1,0),(1,0),(0,-1),(0,1)]
N_ACTIONS = 4